### ISSUE TITLE
AS A developer I NEED TO see a logical file structure in the application SO THAT I can add to it and make changes easily

### ISSUE THREAD

**Issue by arrested-developer** [yalla-coop/rent-check#28]
- [x] original repo is forked / merged in
- [x] server file structure makes sense
- [x] client file structure makes sense

**Comment by thejoefriel** [comment]
For Admin I'd suggest we have a nested folder within our 'components' folder, so something like:

```
|-- components
       |-- Admin
             |-- Users
                    |-- index.js
                    |-- UsersColumns.js
                    |-- Users.style.js
             |-- RentalData
                    |-- index.js
                    |-- AllData.js
                    |-- VerifyData.js
                    |-- RentalDataColumns.js
                    |-- RentalData.style.js
             |-- SideMenu
                    |-- index.js
                    |-- SideMenu.style.js
```

I think we should be able to control the views (e.g. viewing all users vs users awaiting verification) via props, but obviously this could evolve further and there's a clear structure to place additional user related files for admin if props aren't sufficient. 

From experience using antd having a separate Columns component for these sorts of tables is important.
