### ISSUE TITLE
AS A product owner I NEED TO see wireframes of the layout SO THAT I can ask for changes or agree them

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/rent-check#29]
Initial low res wireframes here: 
https://www.figma.com/file/iruatwXo90HOg0uaGAjA2j/East-End-Low-Res?node-id=0%3A1

**Comment by arrested-developer** [comment]
Sent to Krissie today, will update if we get any feedback

**Comment by arrested-developer** [comment]
Closing as we've had no feedback, we can show the admin panel working very soon so let's keep going with the admin components
