### ISSUE TITLE
AS A developer I NEED TO refactor the application to use hooks SO THAT the code style is consistent across old and new components

### ISSUE THREAD

**Issue by arrested-developer** [yalla-coop/rent-check#48]
- [x] existing app components refactored to use hooks
- [x] if any hooks other than setState or useEffect are used, documentation is written in this issue with links or an explanation

**Comment by amusameh** [comment]
### Used Hooks: 
#### useReducer: it's the same as useState but combine more that one state which is related to each others. + how to create custom apiFetch hook
Links: 
https://reactjs.org/docs/hooks-reference.html#usereducer
https://www.robinwieruch.de/react-hooks-fetch-data
